

INSERT INTO public.GENRE (GENRENAME) VALUES ('Комедия');
INSERT INTO public.GENRE (GENRENAME) VALUES ('Драма');
INSERT INTO public.GENRE (GENRENAME) VALUES ('Мультфильм');
INSERT INTO public.GENRE (GENRENAME) VALUES ('Триллер');
INSERT INTO public.GENRE (GENRENAME) VALUES ('Документальный');
INSERT INTO public.GENRE (GENRENAME) VALUES ('Боевик');

INSERT INTO public.MPA (MPANAME) VALUES ('G');
INSERT INTO public.MPA (MPANAME) VALUES ('PG');
INSERT INTO public.MPA (MPANAME) VALUES ('PG-13');
INSERT INTO public.MPA (MPANAME) VALUES ('R');
INSERT INTO public.MPA (MPANAME) VALUES ('NC-17');

